### ISSUE TITLE
config: add CWL config and worker

### ISSUE THREAD

**Issue by diegodelemos** [reanahub/reana-resources-k8s#27]
Once [REANA Workflow Engine CWL](https://github.com/reanahub/reana-workflow-engine-cwl) is ready we should add it to the current [config](https://github.com/reanahub/reana-resources-k8s/blob/master/reana_resources_k8s/templates/config.yaml#L26-L33) along with a new [worker](https://github.com/reanahub/reana-resources-k8s/blob/master/reana_resources_k8s/templates/config.yaml#L61-L78).

**Comment by anton-khodak** [comment]
Should we also modify [workers-template](https://github.com/reanahub/reana-resources-k8s/blob/9a17ce67cb8b2e088e30dcf2d6b7c3effe934163/reana_resources_k8s/templates/deployments/workers-template.yaml#L23)?

**Comment by diegodelemos** [comment]
Indeed, this should be refactored. By the time, when [this](https://github.com/reanahub/reana-workflow-engine-yadage/blob/4d1165d620a720854034e53d4d4ef6f16da7539a/reana_workflow_engine_yadage/externalbackend.py#L113/) was written, the word yardage was included for some reason but for sure it should be `REANA_WORKFLOW_ENGINE_EXPERIMENT` instead. Moreover, most probably it won't be only this that needs to be changed, we should look for the right abstractions :)

**Comment by tiborsimko** [comment]
Closed by #28.
