### ISSUE TITLE
RFC rename to `reana-cluster-resources`

### ISSUE THREAD

**Issue by tiborsimko** [reanahub/reana-resources-k8s#29]
Now that we have `reana-cluster`, what about renaming this package to `reana-cluster-resources`?
(or `reana-cluster-resources-k8s`)

**Comment by diegodelemos** [comment]
I am ok with it. My question is, will the structure look like this?
```console
~/reana-resources-k8s $ tree -L 2
.
├── reana-cluster-resources
│   ├── __init__.py
│   ├── cli.py
│   ├── config.py
│   ├── templates
│   │   ├── kubernetes-resources
│   │   │   ├── deployments
│   │   │   ├── namespaces
│   │   │   ├── resourcequotas
│   │   │   └── services
│   │   ├── mesos-resources
│   │   │   └── ....
│   └── version.py
```
Containing `cli` (or any other module) the operations to generate manifests for any backend and exposing them through `entrypoints` so `reana-cluster` can use them?

**Comment by diegodelemos** [comment]
Closing since `reana-resources-k8s` has been deprecated.
